# fly.toml app configuration file generated for dawn-leaf-4964 on 2023-04-21T18:23:50-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dawn-leaf-4964"
primary_region = "gig"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"
  
[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"